---
version: '3'

services:

  source-zookeeper:
    container_name: source-zookeeper
    extends:
        file: ./../../docker-compose.base.yml
        service: zookeeper


  source-cluster:
    image: confluentinc/cp-server:7.3.0
    container_name: source-cluster
    hostname: source-cluster
    restart: always
    ports:
      - "19092:19092"
      - "18091:8091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:19092,PLAINTEXT://source-cluster:9092
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ZOOKEEPER_CONNECT: 'source-zookeeper:2181'
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Required to enable schema registry
      KAFKA_CONFLUENT_HTTP_SERVER_LISTENERS: http://source-cluster:8090
      # Required to enable schema exporter
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://source-schema-registry:8081

  dest-cluster:
    image: confluentinc/cp-server:7.3.0
    container_name: dest-cluster
    hostname: dest-cluster
    restart: always
    ports:
      - "29092:29092"
      - "28091:8091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://dest-cluster:9092
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ZOOKEEPER_CONNECT: 'dest-zookeeper:2181'
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Required to enable schema registry
      KAFKA_CONFLUENT_HTTP_SERVER_LISTENERS: http://dest-cluster:8090
      # Required to enable schema exporter
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://dest-schema-registry:8081

  dest-zookeeper:
    container_name: dest-zookeeper
    extends:
        file: ./../../docker-compose.base.yml
        service: zookeeper

  source-schema-registry:
    container_name: source-schema-registry
    extends:
        file: ./../../docker-compose.base.yml
        service: schema-registry
    volumes:
      - $PWD/data:/data
    depends_on:
      - source-cluster
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://source-cluster:9092
      SCHEMA_REGISTRY_LISTENERS: http://source-schema-registry:8081
      SCHEMA_REGISTRY_RESOURCE_EXTENSION_CLASS: io.confluent.schema.exporter.SchemaExporterResourceExtension
      SCHEMA_REGISTRY_KAFKASTORE_UPDATE_HANDLERS: io.confluent.schema.exporter.storage.SchemaExporterUpdateHandler
      SCHEMA_REGISTRY_PASSWORD_ENCODER_SECRET: mysecret

  dest-schema-registry:
    container_name: dest-schema-registry
    extends:
        file: ./../../docker-compose.base.yml
        service: schema-registry
    depends_on:
      - dest-cluster
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://dest-cluster:9092
      SCHEMA_REGISTRY_LISTENERS: http://dest-schema-registry:8081
      SCHEMA_REGISTRY_RESOURCE_EXTENSION_CLASS: io.confluent.schema.exporter.SchemaExporterResourceExtension
      SCHEMA_REGISTRY_KAFKASTORE_UPDATE_HANDLERS: io.confluent.schema.exporter.storage.SchemaExporterUpdateHandler
      SCHEMA_REGISTRY_PASSWORD_ENCODER_SECRET: mysecret

      # Required for destionation schema registry
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas1
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_GROUP_ID: schema-registry-dest
