---
version: '3'

services:

  source-zookeeper:
    container_name: source-zookeeper
    extends:
        file: ./../../docker-compose.base.yml
        service: zookeeper


  source-cluster:
    image: confluentinc/cp-server:7.3.0
    container_name: source-cluster
    hostname: source-cluster
    restart: always
    ports:
      - "19092:19092"
      - "18091:8091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:19092,PLAINTEXT://source-cluster:9092
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ZOOKEEPER_CONNECT: 'source-zookeeper:2181'
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_HTTP_SERVER_LISTENERS: http://localhost:8090

  dest-cluster:
    image: confluentinc/cp-server:7.3.0
    container_name: dest-cluster
    hostname: dest-cluster
    restart: always
    ports:
      - "29092:29092"
      - "28091:8091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://dest-cluster:9092
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ZOOKEEPER_CONNECT: 'dest-zookeeper:2181'
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_HTTP_SERVER_LISTENERS: http://localhost:8091

  dest-zookeeper:
    container_name: dest-zookeeper
    extends:
        file: ./../../docker-compose.base.yml
        service: zookeeper


  # Kafka configuration
  # schema-registry:
  #   extends:
  #       file: ./../../docker-compose.base.yml
  #       service: schema-registry
  #   depends_on:
  #     - broker
  #   environment:
  #     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker:29092
  #     SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
